MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    CONV_BODY: "R-50-C4"
    FREEZE_CONV_BODY_AT: -1
  #WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    USE_FPN: False
    ANCHOR_SIZES: (32, 64, 128, 256, 512)

    #ANCHOR_STRIDE: (4,)
    #ANCHOR_STRIDE: (8,)
    ANCHOR_STRIDE: (16,)
    #ANCHOR_STRIDE: (32,)

    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    BATCH_SIZE_PER_IMAGE: 256
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: False
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    POOLER_RESOLUTION: 14
    #POOLER_SCALES: (0.25,)  # 1 / 4
    #POOLER_SCALES: (0.125,)  # 1 / 8
    POOLER_SCALES: (0.0625,)  # 1 / 16
    #POOLER_SCALES: (0.03125,)  # 1 / 32
    NUM_CLASSES: 81
  RESNETS:
    DILATIONS: (1,4,4)
    STEM_FUNC: "StemWithGN"
    TRANS_FUNC: "BottleneckWithGN"

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)

SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 10000

TEST:
  IMS_PER_BATCH: 8
  DETECTIONS_PER_IMG: 100

OUTPUT_DIR: "./out/coco/nopretrain/faster_R50_C4_dilation4_np"
