MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    CONV_BODY: "Custom-C4"

  CUSTOM_RESNET:
    STEM_OUT_CHANNELS: 64
    STEM_CONFIG: [[7,2,3,1], [3,2,1,1]]
    STEM_CHANNELS: [64, 64]
    BODY_CONFIG: [[[3,1,1,1], [3,1,1,1], [3,1,1,1]], [[3,2,1,1], [3,1,1,1], [3,1,1,1], [3,1,1,1]], [[3,2,1,1], [3,1,1,1], [3,1,1,1], [3,1,1,1], [3,1,1,1], [3,1,1,1]]]
    BODY_CHANNELS: [[64, 64, 256], [256, 128, 512], [512, 256, 1024]]
    OUT_CHANNELS: 1024

  RPN:
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (16,)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    BATCH_SIZE_PER_IMAGE: 256
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    POOLER_RESOLUTION: 14
    POOLER_SCALES: (0.0625,)  # 1 / 16
    NUM_CLASSES: 81
  RESNETS:
    TRANS_FUNC: "BottleneckWithGN"  # Need this so C5 head has group norm

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)

SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 10000

TEST:
  IMS_PER_BATCH: 8
  DETECTIONS_PER_IMG: 100

OUTPUT_DIR: "./out/coco/custom/C4_vanilla"
