MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    CONV_BODY: "Custom-C4"

  CUSTOM_RESNET:
    STEM_OUT_CHANNELS: 32
    STEM_CONFIG: [[7,2,3,1], [3,2,1,1]]
    STEM_CHANNELS: [32, 32]
    BODY_CONFIG: [[[3,1,1,1], [3,1,1,1], [3,1,1,1]], [[3,2,1,1], [3,1,1,1], [3,1,1,1], [3,1,1,1]], [[3,2,1,1], [3,1,1,1], [3,1,1,1], [3,1,1,1], [3,1,1,1], [3,1,1,1]]]
    BODY_CHANNELS: [[32, 32, 128], [128, 64, 256], [256, 128, 512]]
    OUT_CHANNELS: 512

  RPN:
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (16,)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    BATCH_SIZE_PER_IMAGE: 256
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    POOLER_RESOLUTION: 14
    POOLER_SCALES: (0.0625,)  # 1 / 16
    NUM_CLASSES: 81
  RESNETS:
    TRANS_FUNC: "BottleneckWithGN"  # Need this so C5 head has group norm
    STRIDE_IN_1X1: False
    RES2_OUT_CHANNELS: 128
    WIDTH_PER_GROUP: 32

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)

SOLVER:
  BASE_LR: 0.01
  #BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  #STEPS: (60000, 80000)
  #MAX_ITER: 90000
  IMS_PER_BATCH: 8
  #IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 10000

TEST:
  IMS_PER_BATCH: 8
  DETECTIONS_PER_IMG: 100

OUTPUT_DIR: "./out/coco/custom/vanilla_C4"
