MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  DONT_LOAD: ["layer3"]
  RPN:
    USE_FPN: False
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (16,)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    BATCH_SIZE_PER_IMAGE: 256
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: False
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    POOLER_RESOLUTION: 14
    POOLER_SCALES: (0.0625,)  # 1 / 16
    NUM_CLASSES: 81

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)

SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (480000, 640000)
  MAX_ITER: 720000
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 100

TEST:
  IMS_PER_BATCH: 2

OUTPUT_DIR: "./logs/test_1x"
