MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  RPN:
    USE_FPN: False
    ANCHOR_SIZES: (32, 64, 128, 256, 512)

    ANCHOR_STRIDE: (24,)
    #ANCHOR_STRIDE: (16,)
    #ANCHOR_STRIDE: (8,)

    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    BATCH_SIZE_PER_IMAGE: 256
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: False
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    POOLER_RESOLUTION: 14

    POOLER_SCALES: (0.0416667,)  # 1 / 24
    #POOLER_SCALES: (0.0625,)     # 1 / 16
    #POOLER_SCALES: (0.125,)      # 1 / 8

    NUM_CLASSES: 81

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)

SOLVER:
  BASE_LR: 0.0075
  WEIGHT_DECAY: 0.0001
  STEPS: (160000, 213000)
  MAX_ITER: 240000
  IMS_PER_BATCH: 6
  CHECKPOINT_PERIOD: 2500

TEST:
  IMS_PER_BATCH: 6

OUTPUT_DIR: "./out/faster_R101_stride24"
