MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  #DONT_LOAD: ["layer3", "layer4"]
  RPN:
    USE_FPN: False
    ANCHOR_SIZES: (16, 32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (16,)
    #ANCHOR_STRIDE: (8,)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    BATCH_SIZE_PER_IMAGE: 256
    PRE_NMS_TOP_N_TRAIN: 40000
    PRE_NMS_TOP_N_TEST: 20000
    POST_NMS_TOP_N_TRAIN: 8000
    POST_NMS_TOP_N_TEST: 4000
  ROI_HEADS:
    USE_FPN: False
    BATCH_SIZE_PER_IMAGE: 512
    DETECTIONS_PER_IMG: 1800
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    POOLER_RESOLUTION: 14
    POOLER_SCALES: (0.0625,)  # 1 / 16
    #POOLER_SCALES: (0.125,)  # 1 / 8
    NUM_CLASSES: 61
  RESNETS:
      MIDDLE_KERNEL_SIZES: []
      # MIDDLE_KERNEL_SIZES: [[3,3,3],[3,3,3,3],[3,3,3,3,3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]]

INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 600
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 600
  

DATASETS:
  TRAIN: ("xView_full_train",)
  TEST: ("xView_full_val",)

SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (480000, 640000)
  MAX_ITER: 720000
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 100

TEST:
  IMS_PER_BATCH: 1

OUTPUT_DIR: "./out/xview/test_1x"
