MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    FPN_POST_NMS_PER_BATCH: False
    PRE_NMS_TOP_N_TRAIN: 8000   # Per FPN level
    PRE_NMS_TOP_N_TEST: 4000    # Per FPN level
    POST_NMS_TOP_N_TRAIN: 8000  # Per image (i think?) this may not even be used
    POST_NMS_TOP_N_TEST: 4000   # Per image (i think?) this may 
    FPN_POST_NMS_TOP_N_TRAIN: 8000  # Per image
    FPN_POST_NMS_TOP_N_TEST: 4000   # Per image
  ROI_HEADS:
    USE_FPN: True
    DETECTIONS_PER_IMG: 1800
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 61

INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 600 
  MIN_SIZE_TEST: 600 
  MAX_SIZE_TEST: 600 

DATASETS:
  TRAIN: ("xView_full_train",)
  TEST: ("xView_full_val",)

DATALOADER:
  SIZE_DIVISIBILITY: 16

SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 100000)
  MAX_ITER: 110000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 5000

TEST:
  IMS_PER_BATCH: 8

OUTPUT_DIR: "./out/xview/fpn_R50"
