MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    CONV_BODY: "STRIDER-FPN"
  STRIDER:
    STEM_CONFIG: [[7,2,3,1], [3,2,1,1]]
    STEM_CHANNELS: [64, 64]
    STEM_OUT_CHANNELS: 64
    BODY_CHANNELS: [[64, 64, 256], [256, 64, 256], [256, 64, 256], [256, 128, 512], [512, 128, 512], [512, 128, 512], [512, 128, 512],[512, 256, 1024], [1024, 256, 1024], [1024, 256, 1024], [1024, 256, 1024], [1024, 256, 1024], [1024, 256, 1024], [1024, 512, 2048], [2048, 512, 2048], [2048, 512, 2048]]
    OUT_CHANNELS: 2048
    FPN_OUT_CHANNELS: 256
    #REG_BOTTLENECKS: [[1, 1], [1, 1], [1, 1],[2, 1], [1, 1], [1, 1], [1, 1],[2, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1],[2, 1], [1, 1], [1, 1]]
    REG_BOTTLENECKS: [[1, 1], [1, 1], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
    STRIDERBLOCK_FUSEINTO_INDEXES: [1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1]
    RETURN_FEATURES: [False, False, True, False, False, False, True, False, False, False, False, False, True, False, False, True]
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    PRE_NMS_TOP_N_TRAIN: 2000   # Per FPN level
    PRE_NMS_TOP_N_TEST: 1000    # Per FPN level     
    POST_NMS_TOP_N_TRAIN: 2000  # Per FPN level
    POST_NMS_TOP_N_TEST: 1000   # Per FPN level
    FPN_POST_NMS_PER_BATCH: False   # True
    FPN_POST_NMS_TOP_N_TRAIN: 1000  # 2000 (if 2 ims/GPU)  Per image
    FPN_POST_NMS_TOP_N_TEST: 1000   # Per image
  ROI_HEADS:
    USE_FPN: True
    DETECTIONS_PER_IMG: 100
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 81
  RESNETS:
    STEM_FUNC: "StemWithGN"
    TRANS_FUNC: "BottleneckWithGN"
DATASETS:
  TRAIN: ("coco_2017_val",)
  TEST: ("coco_2017_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  IMS_PER_BATCH: 2  # 4 GPUs * 2 ims/GPU
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  CHECKPOINT_PERIOD: 10000
TEST:
  IMS_PER_BATCH: 8
  DETECTIONS_PER_IMG: 100

OUTPUT_DIR: "./out/coco/strider/faster_R50_strider_play"
